### PR TITLE
Staking optimizations

### PR DESCRIPTION
**Pull request by HiHat**
Invoke BlockAssembler() and CreateNewBlock() only once per stake by Staker::worker.
Currently they invoked 32 times per stake in 16 sec.

## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The PR doesn't replicate another PR which is already open.
- [ ] The PR has self-explained commits history.

- [ ] The code is mine or it's from somewhere with an Apache-2.0 compatible license.
- [ ] The code is efficient, to the best of my ability, and does not waste computer resources.
- [ ] The code is stable and I have tested it myself, to the best of my abilities.
- [ ] If the code introduces new classes, methods, I provide a valid use case for all of them.

## Changes:

- [...]

## Other comments:

...

### CODE REVIEW

**Comment by HiHat** [comment]
After [staker sleeping fix](https://github.com/pocketnetteam/pocketnet.core/pull/685/commits/bb88bfb718ff043e6d70f49f86d2f78fad00252c) CPU utilization became dramatically low!

**Comment by andyoknen** [comment]
> After [staker sleeping fix](https://github.com/pocketnetteam/pocketnet.core/pull/685/commits/bb88bfb718ff043e6d70f49f86d2f78fad00252c) CPU utilization became dramatically low!

Testing is required. How long has the node been working with these changes? Can you run a node on a test network?

**Comment by HiHat** [comment]
> Testing is required. How long has the node been working with these changes? Can you run a node on a test network?

Optimized node runs smoothly more than a month on main and test network on same low CPU host!
Staking rate not changed and tx validation errors appear only once per 16 sec!

**Comment by andyoknen** [comment]
Result functional tests:

```sh
> python3 ./functional/pocketnet/test_runner.py                                      

Discovered Tests:

  - accounts.py
  - badges.py
  - balance.py
  - barteron.py
  - blockings.py
  - chainbuilder_full_activity.py
  - comments.py
  - content_collections.py
  - contents.py
  - delayed_transactions.py
  - delete_account.py
  - delete_content.py
  - explorer.py
  - feeds.py
  - lottery.py
  - moderation_jury.py
  - moderation_jury_no_ban.py
  - scores.py
  - search.py
  - system.py
  - unsubscribe_deleted_account.py

Running Pocketnet tests using 3 workers...

1/21 - balance.py passed, Duration: 224 s
2/21 - accounts.py passed, Duration: 321 s
3/21 - badges.py passed, Duration: 551 s
4/21 - blockings.py passed, Duration: 294 s
5/21 - barteron.py passed, Duration: 407 s
6/21 - comments.py passed, Duration: 303 s
7/21 - content_collections.py passed, Duration: 591 s
8/21 - contents.py passed, Duration: 336 s
9/21 - delayed_transactions.py passed, Duration: 416 s
10/21 - delete_account.py passed, Duration: 415 s
11/21 - delete_content.py passed, Duration: 287 s
12/21 - explorer.py passed, Duration: 416 s
13/21 - chainbuilder_full_activity.py passed, Duration: 1567 s
14/21 - feeds.py passed, Duration: 368 s
15/21 - moderation_jury.py passed, Duration: 352 s
16/21 - lottery.py passed, Duration: 417 s
17/21 - scores.py passed, Duration: 304 s
18/21 - moderation_jury_no_ban.py passed, Duration: 496 s
Remaining jobs: [search.py, system.py, unsubscribe_deleted_account.py]
19/21 - search.py passed, Duration: 329 s
Remaining jobs: [system.py, unsubscribe_deleted_account.py]
20/21 - system.py passed, Duration: 287 s
Remaining jobs: [unsubscribe_deleted_account.py]
21/21 - unsubscribe_deleted_account.py passed, Duration: 287 s

TEST                           | STATUS    | DURATION

accounts.py                    | ✓ Passed  | 321 s
badges.py                      | ✓ Passed  | 551 s
balance.py                     | ✓ Passed  | 224 s
barteron.py                    | ✓ Passed  | 407 s
blockings.py                   | ✓ Passed  | 294 s
chainbuilder_full_activity.py  | ✓ Passed  | 1567 s
comments.py                    | ✓ Passed  | 303 s
content_collections.py         | ✓ Passed  | 591 s
contents.py                    | ✓ Passed  | 336 s
delayed_transactions.py        | ✓ Passed  | 416 s
delete_account.py              | ✓ Passed  | 415 s
delete_content.py              | ✓ Passed  | 287 s
explorer.py                    | ✓ Passed  | 416 s
feeds.py                       | ✓ Passed  | 368 s
lottery.py                     | ✓ Passed  | 417 s
moderation_jury.py             | ✓ Passed  | 352 s
moderation_jury_no_ban.py      | ✓ Passed  | 496 s
scores.py                      | ✓ Passed  | 304 s
search.py                      | ✓ Passed  | 329 s
system.py                      | ✓ Passed  | 287 s
unsubscribe_deleted_account.py | ✓ Passed  | 287 s

ALL                            | ✓ Passed  | 8968 s (accumulated) 
Runtime: 3078 s
```

**Review by andyoknen — APPROVED** [review]

**Pull request closed without merging**
