### PR TITLE
build: Make $(package)_*_env available to all $(package)_*_cmds (and …

### PR DESCRIPTION
**Pull request by HiHat**
…other fixes to funcs.mk)

Backport from https://github.com/bitcoin/bitcoin/pull/24279 and other

## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The PR doesn't replicate another PR which is already open.
- [ ] The PR has self-explained commits history.

- [ ] The code is mine or it's from somewhere with an Apache-2.0 compatible license.
- [ ] The code is efficient, to the best of my ability, and does not waste computer resources.
- [ ] The code is stable and I have tested it myself, to the best of my abilities.
- [ ] If the code introduces new classes, methods, I provide a valid use case for all of them.

## Changes:

- [...]

## Other comments:

...

### CODE REVIEW

**Comment by HiHat** [comment]
This changes required to QT 5.15 LTS migration and future MacOS builds preparation.

**Comment by andyoknen** [comment]
> This changes required to QT 5.15 LTS migration and future MacOS builds preparation.

Do you have experience building MacOS?

**Review by andyoknen — APPROVED** [review]

**Comment by HiHat** [comment]
> Do you have experience building MacOS?

No, but I think that it possible using backports from bitcoin core (depends packages and build scripts).

**Comment by andyoknen** [comment]
> No, but I think that it possible using backports from bitcoin core (depends packages and build scripts).

I ran into the problem of preparing the SDK until I had time to close this issue.

**Pull request merged**
