### PR TITLE
New transactions (Boost, Article)

### LINKED ISSUE #117: Recommendations API methods
- [ ] Test SQL queries - optimize if necessary. Maximum execution time for different input parameters is 350ms
- [ ] Test API methods, exclude access to empty memory or other situations leading to system crash
- [x] Implement the help text for API methods

### LINKED ISSUE #133: Boost transactions

### LINKED ISSUE #134: Article transaction (Long Post)

### LINKED ISSUE #158: Errors related to notifications

### LINKED ISSUE #166: Enable public API by default
8529d7c9936aac99f0a92b2547ea31721916a90b

### LINKED ISSUE #167: Exclude comments from accounts blocked by the author of the post
2b7ba23e95dc8008b7f954119e4e5dadc9ad7add

### LINKED ISSUE #168: Fix GetPostScores for accounts with 0 rating
8981bf78d8bf81c81a436348bcc5ee57d9005f97

### LINKED ISSUE #169: Remove donations from GetLastComments < 0.5 PKOIN

### LINKED ISSUE #175: After editing the comment, the values of the ratings disappear
Reproduce:
1. Comment post
2. Score Down or Up comment
3. Edit comment

### PR DESCRIPTION
**Pull request by andyoknen**
- [x] Boost Post
- [x] Article Post

### CODE REVIEW

**Comment by andyoknen** [comment]
I encounter unexpected node drops in the test network - unfortunately without details. I'm building a debug version

**Comment by andyoknen** [comment]
@tawmaz @lostystyg The main works are finished - it is necessary to review

**Comment by tawmaz** [comment]
Have these new transactions been tested to not cause a fork in the chain?  If they do cause a fork we should define a block height in the code where they become active (example: 1600000) and bump protocol version, and communicate this to node operators so they have time to update nodes.

**Comment by andyoknen** [comment]
> Have these new transactions been tested to not cause a fork in the chain? If they do cause a fork we should define a block height in the code where they become active (example: 1600000) and bump protocol version, and communicate this to node operators so they have time to update nodes.

By the way, a good note, we forgot to prohibit the processing of such transactions through the ROC. But I think we can go further and ban them at the consensus level so as not to release an additional version. I'll do it in the morning.

Do you have any ideas about the protocol version? I've been wanting to start implementing new functionality for a long time along with changing the protocol version, but I don't have enough time for this

f8e5e447297647c531a50f67c7a22975746b0885

**Review by lostystyg — APPROVED** [review]

**Review by tawmaz — APPROVED** [review]

**Pull request merged**
